---
version: 2.1

# Helpers
defaults: &defaults
  docker:
    - image: mglaman/ci-images:circleci-php7.2-browsers
  working_directory: ~/repo

commands:
  start-project:
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-{{ checksum "composer.json" }}
      - run: composer global require "hirak/prestissimo:^0.3"
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
            - ~/.composer/cache
          key: composer-{{ checksum "composer.json" }}
      - run:
          name: Create testing directories
          command: |
            mkdir -p sites/simpletest
            mkdir -p private/reports
            mkdir -p private/browser_output
  chromedriver:
    steps:
      - run:
          name: Start ChromeDriver
          command: chromedriver
          background: true
  builtin_server:
    steps:
      - run:
          name: Start builtin
          command: php -S 127.0.0.1:8080 -t web
          background: true
  behat:
    steps:
      - builtin_server
      - chromedriver
      - run:
          name: Behat
          command: |
            ./vendor/bin/behat -c behat.ci.yml -f junit -o tests/results -f pretty -o std
          when: always
      - run:
          name: Export error logs
          command: |
            ./vendor/bin/drush wd-show
          when: on_fail
      - store_test_results:
          path: tests/results
      - store_artifacts:
          path: tests/failures
jobs:
  build:
    <<: *defaults
    steps:
      - start-project
      - run:
          name: Install should pass.
          command: php scripts/quickstart install
      - run:
          name: Clean
          command: php scripts/clean
      - run:
          name: Package it up
          command: |
            mkdir /tmp/artifacts;
            tar --exclude=".git" --exclude="node_modules" -czvf /tmp/artifacts/demo-project.tar.gz .
            zip -r /tmp/artifacts/demo-project.zip . -x node_modules/\* -1
      - store_artifacts:
          path: /tmp/artifacts
  behat:
    <<: *defaults
    steps:
      - start-project
      - run:
          name: Disable xdebug, bump memory_limit
          command: |
            sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            echo 'memory_limit=-1' | sudo tee -a /usr/local/etc/php/php.ini
      - run:
          name: Setup the database
          command: |
            ./vendor/bin/drush si --account-pass=admin --yes
      - behat
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - behat
